In [2]:
import numpy as np

Dimension

In [2]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) 

0
1
2
3


Indexing

In [5]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2]) 

arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr2[-1,-1])

6
Last element from 2nd dim:  10


Slicing

In [ ]:
# s_arr = np.array([1, 2, 3, 4, 5, 6, 7])

# print(s_arr[2:4])
# print(s_arr[4:])
# print(s_arr[:4])
# print(s_arr[-6:-1])

# # step
# #start, stop, step var
# print(s_arr[1:5:2]) 


# print(s_arr[::4])

# s_2d_arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# print(s_2d_arr[1, 1:4]) 


[3 4]
[5 6 7]
[1 2 3 4]
[2 3 4 5 6]
[2 4]
[1 5]
[7 8 9]


Data type
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [30]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype) 

arr_two = np.array([1,2,3,4], dtype='S')
print(arr_two.dtype)

arr_three = np.array([1.9, 2.1, 3.1])

new_arr_three = arr_three.astype('i')

print(arr_three)
print(new_arr_three) 


int64
|S1
[1.9 2.1 3.1]
[1 2 3]


Array Copy vs View
Copy: Make a copy, change the original array, and display both arrays
View: Make a view, change the original array, and display both arrays

In [3]:
arr_cv = np.array([1, 2, 3, 4, 5])
x = arr_cv.copy()
y = arr_cv.view()
arr_cv[0] = 42
print(arr_cv)
print(x)
print(y)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]


Reshape From 1-D to 2-D

In [7]:
ex_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

ex_arr_2d = ex_arr.reshape(4, 3)
ex_arr_3d = ex_arr.reshape(2, 3, 2)
print("2d")
print(ex_arr_2d)
print("3d")
print(ex_arr_3d)


2d
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
3d
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Iterating array

In [12]:
arr_i = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

arr_i_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


print('2d')
for x in np.nditer(arr_i):
  print(x) 

print('2d with range')
for x in np.nditer(arr_i[:, ::2]):
  print(x) 
print('3d')
for x in np.nditer(arr_i_3d):
  print(x) 

2d
1
2
3
4
5
6
7
8
2d with range
1
2
5
6
3d
1
2
3
4
5
6
7
8


NumPy Joining Array

In [23]:
arr_j1_2d = np.array([[1, 2], [3, 4]])

arr_j2_2d = np.array([[5, 6], [7, 8]])

# concatenate()
# default axis
arr_j_2d_da = np.concatenate((arr_j1_2d, arr_j2_2d))

arr_j_2d = np.concatenate((arr_j1_2d, arr_j2_2d), axis=1)

print('default axis=> 0 by default')
print(arr_j_2d_da)
print('axis defined')
print(arr_j_2d)







default axis=> 0 by default
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
axis defined
[[1 2 5 6]
 [3 4 7 8]]


In [27]:
#stack-> Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
arr_js1 = np.array([1, 2, 3])

arr_js2 = np.array([4, 5, 6])

arr_js = np.stack((arr_js1, arr_js2), axis=1)

arr_js_row = np.hstack((arr_js1, arr_js2))
arr_js_col = np.vstack((arr_js1, arr_js2))
# Along Height (depth)
arr = np.dstack((arr_js1, arr_js2))


print('stack example')
print(arr_js) 
print('stack row')
print(arr_js_row)
print('stack column')
print(arr_js_col)
print('Along Height (depth)')
print(arr_js_col)

stack example
[[1 4]
 [2 5]
 [3 6]]
stack row
[1 2 3 4 5 6]
stack column
[[1 2 3]
 [4 5 6]]
Along Height (depth)
[[1 2 3]
 [4 5 6]]


Split

In [ ]:
arr_s = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

#Split the 2-D array into three 2-D arrays.
newarr_s = np.array_split(arr_s, 3)

print(newarr_s) 

#hsplit, Note: Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


Searching Arrays

In [ ]:

arr_find_index = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr_find_index == 4)
# x = np.where(arr%2 == 0) -> can also pass in conditions
print(x)

(array([3, 5, 6]),)


In [34]:
# searchsorted()
arr_ss = np.array([6, 7, 8, 9])

arr_ss_final = np.searchsorted(arr_ss, 7)
# search starting from the right
# arr_ss_final = np.searchsorted(arr, 7, side='right') 
print(arr_ss_final)


#which positions should 2, 4, 10 be inserted
positions = np.searchsorted(arr_ss, [2, 4, 10])

print(positions) 

1
[0 0 4]


Sorting a 2-D Array

In [35]:

arr_sort = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr_sort)) 

[[2 3 4]
 [0 1 5]]


Filtering Array Simple Example

In [36]:
arr_initial = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

filtered_arr = arr[filter_arr]

print(filter_arr)
print(filtered_arr) 

[[[False  True]
  [ True False]
  [False  True]]]
[4 2 6]
